version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DOCKER_REGISTRY_URL: "https://registry.cscloud.biz"
      DOCKER_USERNAME: "csadmin"
      DOCKER_PASSWORD: "cs@admin"
    volumes:
      - ./backend:/app/backend

  frontend:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
